server:
  port: 3000
  basePath: ''
application:
  domain: shop-se.co
  name: 'The SECO Summer Shop'
  logo: JuiceShop_Logo.png
  favicon: favicon_js.ico
  theme: purple-green # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: false
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: SECOin
  privacyContactEmail: donotreply@shop-se.co
  customMetricsPrefix: secoshop
  chatBot:
    name: 'Secy'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'https://owasp.org/slack/invite'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    nftUrl: 'https://opensea.io/collection/juice-shop'
    questionnaireUrl: ~
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to the SECO Summer Shop'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>OWASP Juice Shop</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications. The <strong>OWASP Juice Shop</strong> is an open-source project hosted by the non-profit <a href='https://owasp.org' target='_blank'>Open Web Application Security Project (OWASP)</a> and is developed and maintained by volunteers. Check out the link below for more information and documentation on the project.</p><h1><a href='https://owasp-juice.shop' target='_blank'>https://owasp-juice.shop</a></h1>"
  cookieConsent:
    backgroundColor: '#546e7a'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@shop-se.co'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
    hiring: '/#/jobs'
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'Broken Access Ball'
    description: 'This ball apparently has an owner and should only be used by this owner but everybody is playing with, and so can you!'
    price: 3.99
    image: ball.png
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
    reviews:
      - { text: 'This ball is amazingly round and allows me to play games with my friends!', author: admin }
  -
    name: 'Burp Blanket'
    description: 'A nice, soft blanket that can be used on the beach.'
    price: 9.99
    image: blanket.png
    useForChristmasSpecialChallenge: true
  -
    name: 'Coens Coconut Drink'
    description: 'A refreshing drink server in a beautiful coconut.'
    price: 2.99
    image: coconut.png
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'SECO Floaty'
    description: 'A special edition floaty to take out to the pool this summer! A blue unicorn that will impress everyone.'
    price: 4.99
    image: floaty.png
    reviews:
      - { text: 'I straight-up gots nuff props fo''this floaty yo', author: rapper }
  -
    name: 'Ice Cream'
    description: '1x20 ice creams with an unique taste explotion that will rock your world.'
    price: 4.99
    quantity: 5
    limitPerUser: 5
    image: ijsco.png
    reviews:
      - { text: 'This ice cream is the best tasting thing in the history of the world!', author: rapper }
      - { text: 'If I could only have one snack for the rest of my life, this is the one.', author: jim }
  -
    name: 'RESC Shirt'
    description: 'This RESC Hawaii shirt was designed by the Open Source Community with more stars being printed on the shirt daily.'
    price: 19.99
    image: shirt.png
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  -
    name: 'Ingmars Sunchair'
    description: 'An amazing chair to kick back and relax in. Great to sit in the garden with the laptop to hand out waivers! '
    price: 39.99
    quantity: 8
    image: sunchair.png
    reviews:
      - { text: 'Cannot wait to get one of these for myself!', author: bjoernOwasp }
  -
    name: 'SECO Sunscreen'
    description: 'This sunscreen protects you from the sun! It is perfect for every body type and a 100 percent guarentee that it works!'
    price: 3.99
    quantity: 3
    image: sunscreen.png
    reviews:
      - { text: "Its a nice and soft sunscreen.", author: rapper }
  -
    name: 'Secure Swimming Shorts'
    description: "These swimming shorts are so secure they you will not lose them! You need to make use of 2FA to unbutton it."
    price: 14.99
    quantity: 0
    image: swimmingshorts.png
    reviews:
      - { text: "Rad, dude!", author: rapper }
      - { text: "The perfect fit!", author: jim }
      - { text: "I lost mine in the ocean..", author: bender }
  -
    name: 'Peters Parasol'
    description: "An amazing parasol for the beach or at home to relax in the shade and not get sunburned!"
    price: 49.99
    quantity: 0
    limitPerUser: 1
    image: umbrella.png
    reviews:
      - { text: "Keeps you from turning red!", author: uvogin }
      - { text: "It flew away!!", author: bender }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[̲̅$̲̅(̲̅-͡°-͜ʖ-͡°̲̅)̲̅$̲̅]-1572603645543.jpg'
    caption: 'My rare collectors item! [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
